languageCode: "en-us"
title: "ScreepsPlus"
# theme: "blackburn"
theme: ScreepsPlus

baseURL: https://screepspl.us/

canonifyurls: true
paginate: 10
enableEmoji: true
enableGitInfo: true

indexes:
  tag: "tags"
  topic: "topics"

params:
  subtitle: ""
  brand: "ScreepsPlus"
  custom_css: ["css/my.css"]
  description: "ScreepsPlus Graphs and Servers"
  # custom_js: ["js/my.js"]

menu:
  main:
  - name: "Services"
    pre: "<i class='fa fa-chevron-right fa-fw'></i>"
    itentifier: "services"
    weight: 10
  - name: "External"
    pre: "<i class='fa fa-external-link fa-fw'></i>"
    weight: 50
  - name: "Home"
    pre: "<i class='fa fa-home fa-fw'></i>"
    weight: 1
    identifier: "home"
    url: "/"
  - name: "Forum"
    pre: "<i class='fa fa-comments fa-fw'></i>"
    weight: 80
    identifier: "forum"
    url: "https://screeps.com/forum/category/25/screepsplus"
    parent: External
  - name: "Wiki"
    pre: "<i class='fa fa-book fa-fw'></i>"
    weight: 50
    identifier: "wiki"
    url: "https://wiki.screepspl.us"
    parent: External
  - name: Account
    pre: "<i class='fa fa-user fa-fw'></i>"
    weight: 90
  - name: 'Signin/Logout'
    pre: "<i class='fa fa-sign-in fa-fw'></i>"
    weight: 10
    url: "/login"
    parent: Account
  - name: 'Grafana'
    pre: "<i class='fa fa-line-chart fa-fw'></i>"
    url: "/grafana"
    parent: Account
    

social:
  twitter: "ags131"
  github: "ScreepsPlus"
  patreon: "ags131"
  slack: "C2FD5CGJV"
